export const screensNames = {
  welcome: 'Welcome',
  singIn: 'SingIn',
  singUp: 'SingUp',
  drawerNavigator: 'DrawerNavigator',
  profile: 'Profile',
  homeScreen: 'HomeScreen',
  campaignsScreen: 'CampaignsScreen',
  donatorsScreen: 'DonatorsScreen',
  requestsScreen: 'RequestsScreen',
  helpScreen: 'HelpScreen',
  aboutScreen: 'AboutScreen',
  contactUsScreen: 'ContactUsScreen',
  donators: 'Donators',
  requests: 'Requests',
  addRequest: 'AddRequest',
  addPost: 'AddPost',
  addCampaign: 'AddCampaign',
  profileEdit:'ProfileEdit',
  topTabsNavigator: {
    addMessage: 'AddMessage',
    messages: 'Messages',
  },
};
